# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'rn_compile_error' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for rn_compile_error
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge',
    'ART',
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
#    'BatchedBridge', # already removed
    'RCTText',
    'RCTImage',
    'RCTNetwork',
    'RCTWebSocket', # needed for debugging
    'RCTPushNotification',
    'RCTBlob',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTSettings',
    'RCTLinkingIOS',
    'RCTGeolocation',
    'RCTAnimation',
    'tvOS',
    # Add any other subspecs you want to use in your project
  ]
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

end

